package com.jjongjjongs.minimobile;

import android.content.Context;
import android.content.res.AssetFileDescriptor;
import android.media.AudioAttributes;
import android.media.AudioFormat;
import android.media.AudioManager;
import android.media.AudioTrack;
import android.media.MediaPlayer;
import android.media.SoundPool;
import android.os.Build;
import android.os.SystemClock;
import android.util.Log;

import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

final class ZenoniaAudioOverride {
    private static final String TAG = "WIE-ZenoniaAudio";

    /**
     * Whether the bundled-recording override is live. Off means the emulator's
     * own audio — the MA-3 synthesiser, its recorded drums, and the ADPCM wave
     * clips decoded straight out of a title's {@code .mmf} — is heard as-is,
     * with nothing swapped in. Kept as a switch so the substituted sound can be
     * put back for comparison; when the emulator's audio is confirmed to stand
     * on its own, this class and the recordings it draws on come out entirely.
     */
    private static final boolean ENABLED = false;

    private static final String ASSET_DIR = "zenonia1/";
    private static final int ZENONIA2_CLIP_BASE = 2000;
    private static final int ZENONIA3_CLIP_BASE = 3000;

    private static final Map<Long, Integer> PCM_CLIPS = new HashMap<>();
    private static final Map<String, Integer> MIDI_CLIPS = new HashMap<>();
    private static final Map<Integer, Integer> SOUND_IDS = new HashMap<>();
    private static final Map<Integer, Long> DURATIONS_MS = new HashMap<>();
    private static final Set<String> DIAGNOSTICS = new HashSet<>();
    private static final List<AudioTrack> NATIVE_WAVE_TRACKS = new ArrayList<>();

    private static Context context;
    private static SoundPool soundPool;
    private static MediaPlayer musicPlayer;
    private static long midiMutedUntil;

    private ZenoniaAudioOverride() {}

    static synchronized void initialize(Context appContext) {
        PerformanceTuner.initialize(appContext);
        if (soundPool != null) {
            return;
        }
        context = appContext.getApplicationContext();
        AudioAttributes attributes = new AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build();
        soundPool = new SoundPool.Builder()
                .setMaxStreams(12)
                .setAudioAttributes(attributes)
                .build();

        addPcm(0, 8000, 6898, 0x9b30f35d1b49c620L);
        addPcm(1, 11025, 3340, 0x2f87c5f874bcbff6L);
        addPcm(2, 11025, 4688, 0xaa02fd0e06d3ad44L);
        addPcm(3, 11025, 2768, 0xd33b07e4021efa59L);
        addPcm(4, 11025, 8098, 0x06817affd84ad3b7L);
        addPcm(5, 11025, 6512, 0xd3f0a40942af6695L);
        addPcm(6, 11025, 5280, 0xca7b02e62756b906L);
        addPcm(7, 11025, 6434, 0xec170a7bf030a075L);
        addPcm(11, 8000, 4524, 0x8075304966e1770fL);
        addPcm(12, 8000, 3222, 0x9aabacbd38ffffb1L);
        addPcm(13, 8000, 2120, 0xc1ab223839004bd4L);
        addPcm(19, 8000, 8906, 0x97e9d4c8807a7634L);
        addPcm(22, 8000, 928, 0x403dba1a44b31cb5L);
        addPcm(24, 8000, 4184, 0xae4b62555509e5a2L);
        addPcm(25, 11025, 6008, 0x097313416c90dd9cL);
        addPcm(26, 11025, 10208, 0xbd37fbea29dfca55L);
        addPcm(27, 11025, 7164, 0xc3c5975aaf27737bL);
        addPcm(28, 8000, 5306, 0x9bb3d37f5a519b53L);
        addPcm(29, 8000, 1788, 0x52e013953160aa09L);
        addPcm(30, 8000, 5598, 0xfca16d8f00add42aL);
        addPcm(31, 8000, 6178, 0xf3a7cd3ccfc38e9aL);
        addPcm(32, 8000, 5598, 0xfca16d8f00add42aL);
        addPcm(33, 11025, 2768, 0xd33b07e4021efa59L);
        addPcm(34, 8000, 3560, 0xacfeb53436f428acL);
        addPcm(35, 8000, 3424, 0xdf54ee26d0902e53L);
        addPcm(36, 8000, 2958, 0x25cc51b32796cfb6L);
        addPcm(103, 11025, 8066, 0x26ff4acf63f44aa4L);

        // Fingerprints generated by the same SMAF decoder used by WIE. The
        // replacement files come from the matching Android remasters.
        addPcm(ZENONIA2_CLIP_BASE + 1, 11025, 3532, 0x866e58f2b1656f4dL);
        addPcm(ZENONIA2_CLIP_BASE + 2, 11025, 5344, 0xe96182d83f1b36d0L);
        addPcm(ZENONIA2_CLIP_BASE + 3, 11025, 5232, 0xd957fd5e804b0450L);
        addPcm(ZENONIA2_CLIP_BASE + 4, 11025, 11880, 0xf6a091d6b28d3f5aL);
        addPcm(ZENONIA2_CLIP_BASE + 5, 8000, 5156, 0x5820ec05ecbf5b07L);
        addPcm(ZENONIA2_CLIP_BASE + 6, 8000, 6336, 0x032637fe32d9d353L);
        addPcm(ZENONIA2_CLIP_BASE + 7, 8000, 2464, 0xfd20031649a4ec1fL);
        addPcm(ZENONIA2_CLIP_BASE + 8, 11025, 3064, 0x3d51fe21dfd1758dL);
        addPcm(ZENONIA2_CLIP_BASE + 9, 8000, 5376, 0x40792cf98f983255L);
        addPcm(ZENONIA2_CLIP_BASE + 10, 11025, 3000, 0x2609276c88638638L);
        addPcm(ZENONIA2_CLIP_BASE + 11, 11025, 2332, 0xefd8df344ff69b3aL);
        addPcm(ZENONIA2_CLIP_BASE + 12, 11025, 8304, 0x00bf3ecb0bc56e19L);
        addPcm(ZENONIA2_CLIP_BASE + 13, 11025, 5280, 0xa6efb6e02163e0d5L);

        addPcm(ZENONIA3_CLIP_BASE + 1, 11025, 4738, 0x91aa66e81e9bdef5L);
        addPcm(ZENONIA3_CLIP_BASE + 2, 11025, 5886, 0x90cd440d707d104fL);
        addPcm(ZENONIA3_CLIP_BASE + 3, 11025, 9174, 0xc48b9fe122cc0eadL);
        addPcm(ZENONIA3_CLIP_BASE + 4, 11025, 8604, 0x87f4e9bd2e3d5070L);
        addPcm(ZENONIA3_CLIP_BASE + 5, 11025, 9174, 0x5b15c3f24903533fL);
        addPcm(ZENONIA3_CLIP_BASE + 6, 11025, 3586, 0x13e61e5b653286b6L);
        addPcm(ZENONIA3_CLIP_BASE + 7, 11025, 4952, 0x1e25c19613f97688L);
        addPcm(ZENONIA3_CLIP_BASE + 8, 11025, 3588, 0xab46096351dbde0eL);
        addPcm(ZENONIA3_CLIP_BASE + 9, 11025, 9164, 0x82668645e3bfcd8aL);
        addPcm(ZENONIA3_CLIP_BASE + 11, 11025, 6286, 0xa318d896421b695bL);
        addPcm(ZENONIA3_CLIP_BASE + 12, 11025, 5050, 0x4d560d6b40b93511L);
        addPcm(ZENONIA3_CLIP_BASE + 13, 11025, 7390, 0xd307dc71ccf84937L);
        addPcm(ZENONIA3_CLIP_BASE + 14, 8000, 8378, 0x83144bd0426fb70aL);
        addPcm(ZENONIA3_CLIP_BASE + 15, 11025, 6618, 0x8bdc922f61bc4334L);
        addPcm(ZENONIA3_CLIP_BASE + 16, 11025, 12444, 0x0e91cd03d75d73c9L);
        addPcm(ZENONIA3_CLIP_BASE + 35, 11025, 6682, 0x19e39b454f68b5bfL);
        addPcm(ZENONIA3_CLIP_BASE + 36, 11025, 5050, 0x6ecd11d2e6783f00L);

        addMidi(8, "f04379067f017c010b000012");
        addMidi(9, "f04379067f017c0127000002");
        addMidi(10, "f04379067f017d0002550103");
        addMidi(14, "f04379067f017c013a000004");
        addMidi(15, "f04379067f017c0163000004");
        addMidi(16, "f04379067f017c0162000000");
        addMidi(17, "f04379067f017d00020f0133");
        addMidi(18, "f04379067f017c011b000002");
        addMidi(20, "f04379067f017c0158000017");
        addMidi(21, "f04379067f017c016e000002");
        addMidi(23, "f04379067f017c0151000002");
        addMidi(37, "f04379067f017c012e000004");
        addMidi(38, "f04379067f017d0002170133");
        addMidi(39, "f04379067f017c0124000017");
        addMidi(40, "f04379067f017c0167000003");
        addMidi(41, "f04379067f017c0115000017");
        addMidi(100, "f04379067f017c015f000002");
        addMidi(101, "f04379067f017c0164000012");
        addMidi(102, "f04379067f017c0128000002");
        addMidi(104, "f04379067f017c016a000002");
        addMidi(105, "f04379067f017c0160000016");
        addMidi(106, "f04379067f017c0157000002");
        addMidi(107, "f04379067f017d0002540123");
        addMidi(108, "f04379067f017c0156000002");

        for (int id = 0; id <= 41; id++) {
            preloadEffect(id);
        }
        preloadEffect(103);
        for (int id : new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}) {
            preloadEffect(ZENONIA2_CLIP_BASE + id);
        }
        for (int id : new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16}) {
            preloadEffect(ZENONIA3_CLIP_BASE + id);
        }
        preloadEffect(ZENONIA3_CLIP_BASE + 35);
        preloadEffect(ZENONIA3_CLIP_BASE + 36);
        NativeWaveBridge.install();
        Log.i(TAG, "initialized exact Zenonia 1 WAV map");
    }

    // 0 = use normal WIE audio, 1 = consumed, 2 = consumed and reset MIDI synth.
    static synchronized int handle(byte[] command) {
        if (!ENABLED) {
            return 0;
        }
        NativeWaveBridge.install();
        if (soundPool == null || command == null || command.length == 0) {
            return 0;
        }

        int opcode = command[0] & 0xff;
        if (DIAGNOSTICS.size() < 200) {
            logOnce("CMD " + opcode + ":" + command.length + ":"
                    + hex(command, 0, Math.min(command.length, 20)));
        }
        if (opcode == 1 && command.length >= 10) {
            int sampleRate = readInt(command, 2);
            int sampleCount = Math.min(readInt(command, 6), (command.length - 10) / 2);
            long fingerprint = fnv1a(command, 10, sampleCount * 2);
            logOnce("PCM " + sampleRate + ":" + sampleCount + ":" + String.format("%016x", fingerprint));
            Integer clip = PCM_CLIPS.get(pcmKey(sampleRate, sampleCount, fingerprint));
            if (clip != null) {
                play(clip);
                if (clip == 0) {
                    midiMutedUntil = SystemClock.uptimeMillis() + duration(clip);
                    return 2;
                }
                return 1;
            }
            return 0;
        }

        if (opcode >= 2 && opcode <= 7) {
            if (opcode == 7) {
                logOnce("SYSEX " + hex(command, 1, Math.min(command.length - 1, 24)));
            }
            Integer clip = opcode == 7 ? findMidiClip(command) : null;
            if (clip != null) {
                play(clip);
                midiMutedUntil = SystemClock.uptimeMillis() + duration(clip);
                return 2;
            }
            if (SystemClock.uptimeMillis() < midiMutedUntil) {
                return 1;
            }
        }
        return 0;
    }

    static synchronized void pause() {
        if (musicPlayer != null && musicPlayer.isPlaying()) {
            musicPlayer.pause();
        }
        if (soundPool != null) {
            soundPool.autoPause();
        }
    }

    static synchronized void resume() {
        if (soundPool != null) {
            soundPool.autoResume();
        }
        if (musicPlayer != null) {
            try {
                musicPlayer.start();
            } catch (IllegalStateException ignored) {
            }
        }
    }

    static synchronized void release() {
        if (musicPlayer != null) {
            musicPlayer.release();
            musicPlayer = null;
        }
        // AndroidAudioOutput is shared while individual WIPI games are
        // stopped and started. Keep the preloaded effect pool alive so the
        // next game can use the same fingerprint map without rebuilding it.
        DIAGNOSTICS.clear();
        for (AudioTrack track : NATIVE_WAVE_TRACKS) {
            try { track.stop(); } catch (RuntimeException ignored) {}
            track.release();
        }
        NATIVE_WAVE_TRACKS.clear();
        midiMutedUntil = 0;
    }

    static synchronized boolean handleNativeWave(int sampleRate, int sampleCount, long fingerprint, short[] pcm) {
        if (!ENABLED) {
            return false;
        }
        cleanupNativeWaves();
        Integer clip = PCM_CLIPS.get(pcmKey(sampleRate, sampleCount, fingerprint));
        if (clip != null && soundPool != null) {
            play(clip);
            Log.i(TAG, "native WAV replacement " + clip + " " + sampleRate + ":" + sampleCount);
            return true;
        }
        // Let the normal WIE path handle effects absent from all remaster
        // fingerprint tables instead of consuming them here.
        return false;
    }

    private static boolean playNativeWave(int sampleRate, short[] pcm) {
        if (pcm == null || pcm.length == 0 || sampleRate < 4000 || sampleRate > 192000) return false;
        try {
            AudioTrack track;
            if (Build.VERSION.SDK_INT >= 26) {
                track = new AudioTrack.Builder()
                        .setAudioAttributes(new AudioAttributes.Builder()
                                .setUsage(AudioAttributes.USAGE_GAME)
                                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                                .build())
                        .setAudioFormat(new AudioFormat.Builder()
                                .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
                                .setSampleRate(sampleRate)
                                .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
                                .build())
                        .setBufferSizeInBytes(pcm.length * 2)
                        .setTransferMode(AudioTrack.MODE_STATIC)
                        .build();
            } else {
                track = new AudioTrack(AudioManager.STREAM_MUSIC, sampleRate,
                        AudioFormat.CHANNEL_OUT_MONO, AudioFormat.ENCODING_PCM_16BIT,
                        pcm.length * 2, AudioTrack.MODE_STATIC);
            }
            if (track.getState() != AudioTrack.STATE_INITIALIZED) {
                track.release();
                return false;
            }
            int written = track.write(pcm, 0, pcm.length, AudioTrack.WRITE_BLOCKING);
            if (written <= 0) {
                track.release();
                return false;
            }
            track.setVolume(1.0f);
            track.play();
            NATIVE_WAVE_TRACKS.add(track);
            Log.d(TAG, "native PCM direct " + sampleRate + ":" + pcm.length);
            return true;
        } catch (RuntimeException error) {
            Log.e(TAG, "native PCM direct failed", error);
            return false;
        }
    }

    private static void cleanupNativeWaves() {
        Iterator<AudioTrack> iterator = NATIVE_WAVE_TRACKS.iterator();
        while (iterator.hasNext()) {
            AudioTrack track = iterator.next();
            if (track.getPlayState() != AudioTrack.PLAYSTATE_PLAYING) {
                track.release();
                iterator.remove();
            }
        }
    }

    private static void addPcm(int clip, int rate, int count, long fingerprint) {
        PCM_CLIPS.put(pcmKey(rate, count, fingerprint), clip);
    }

    private static void addMidi(int clip, String prefix) {
        MIDI_CLIPS.put(prefix, clip);
    }

    private static long pcmKey(int rate, int count, long fingerprint) {
        long mixed = fingerprint ^ ((long) rate << 32) ^ (count & 0xffffffffL);
        mixed ^= mixed >>> 33;
        mixed *= 0xff51afd7ed558ccdL;
        mixed ^= mixed >>> 33;
        return mixed;
    }

    private static void preloadEffect(int clip) {
        try (AssetFileDescriptor descriptor = context.getAssets().openFd(assetName(clip))) {
            int soundId = soundPool.load(descriptor, 1);
            SOUND_IDS.put(clip, soundId);
            DURATIONS_MS.put(clip, wavDuration(descriptor.getLength()));
        } catch (IOException error) {
            Log.e(TAG, "effect preload failed: " + clip, error);
        }
    }

    private static void play(int clip) {
        Integer soundId = SOUND_IDS.get(clip);
        if (soundId != null) {
            soundPool.play(soundId, 1.0f, 1.0f, 1, 0, 1.0f);
            Log.d(TAG, "WAV effect " + clip);
            return;
        }
        try {
            if (musicPlayer != null) {
                musicPlayer.release();
            }
            AssetFileDescriptor descriptor = context.getAssets().openFd(assetName(clip));
            MediaPlayer player = new MediaPlayer();
            player.setAudioAttributes(new AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_GAME)
                    .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                    .build());
            player.setDataSource(descriptor.getFileDescriptor(), descriptor.getStartOffset(), descriptor.getLength());
            DURATIONS_MS.put(clip, wavDuration(descriptor.getLength()));
            descriptor.close();
            player.prepare();
            player.start();
            musicPlayer = player;
            Log.d(TAG, "WAV music " + clip);
        } catch (IOException | IllegalStateException error) {
            Log.e(TAG, "music playback failed: " + clip, error);
        }
    }

    private static Integer findMidiClip(byte[] command) {
        String hex = hex(command, 1, Math.min(command.length - 1, 12));
        for (Map.Entry<String, Integer> entry : MIDI_CLIPS.entrySet()) {
            if (hex.startsWith(entry.getKey())) {
                return entry.getValue();
            }
        }
        return null;
    }

    private static long duration(int clip) {
        Long value = DURATIONS_MS.get(clip);
        if (value != null) {
            return value;
        }
        try (AssetFileDescriptor descriptor = context.getAssets().openFd(assetName(clip))) {
            long result = wavDuration(descriptor.getLength());
            DURATIONS_MS.put(clip, result);
            return result;
        } catch (IOException ignored) {
            return 1000;
        }
    }

    private static long wavDuration(long byteLength) {
        return Math.max(1, ((byteLength - 44) * 1000L) / (22050L * 2L));
    }

    private static String assetName(int clip) {
        if (clip >= ZENONIA3_CLIP_BASE) {
            return "zenonia3/" + String.format("s%03d.mp3", clip - ZENONIA3_CLIP_BASE);
        }
        if (clip >= ZENONIA2_CLIP_BASE) {
            return "zenonia2/" + String.format("s%03d.wav", clip - ZENONIA2_CLIP_BASE);
        }
        return ASSET_DIR + String.format("s%03d.wav", clip);
    }

    private static int readInt(byte[] buffer, int offset) {
        return (buffer[offset] & 0xff)
                | ((buffer[offset + 1] & 0xff) << 8)
                | ((buffer[offset + 2] & 0xff) << 16)
                | ((buffer[offset + 3] & 0xff) << 24);
    }

    private static long fnv1a(byte[] data, int offset, int count) {
        long hash = 0xcbf29ce484222325L;
        int end = Math.min(data.length, offset + count);
        for (int i = offset; i < end; i++) {
            hash ^= data[i] & 0xffL;
            hash *= 0x100000001b3L;
        }
        return hash;
    }

    private static String hex(byte[] data, int offset, int count) {
        StringBuilder result = new StringBuilder(count * 2);
        int end = Math.min(data.length, offset + count);
        for (int i = offset; i < end; i++) {
            result.append(String.format("%02x", data[i] & 0xff));
        }
        return result.toString();
    }

    private static void logOnce(String value) {
        if (DIAGNOSTICS.add(value)) {
            Log.i(TAG, value);
        }
    }
}
