//! Where each platform class keeps its virtual methods in a dispatch table.
//!
//! A class's own methods start at slot 10, after `<init>` and
//! `java/lang/Object`'s nine. Which of *its* methods lands where is decided by
//! the platform, over the class's whole method table - and the table an
//! application registers lists only the methods it imports, so numbering the
//! imported ones in order gets the right answer only for a class an
//! application uses completely.
//!
//! Legend of Master reaches `java/lang/String` slot 16 and imports none of
//! `String`'s virtual methods, so nothing in the application says what slot 16
//! is. It is `compareTo`.
//!
//! Read out of `liblgt_system.so`, whose `dt_<class>` symbols are the tables
//! themselves and whose method tables give the descriptors. A class that is
//! not here falls back to numbering the imported methods in order.

/// One slot: where it is, and the method that sits there.
type Slot = (u32, &'static str, &'static str);

/// `(class, slots in order)`.
pub const PLATFORM_DISPATCH_SLOTS: &[(&str, &[Slot])] = &[
    (
        "java/lang/Object",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
        ],
    ),
    (
        "java/lang/Class",
        &[
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "newInstance", "()Ljava/lang/Object;"),
            (11, "isInstance", "(Ljava/lang/Object;)Z"),
            (12, "isAssignableFrom", "(Ljava/lang/Class;)Z"),
            (13, "isInterface", "()Z"),
            (14, "isArray", "()Z"),
            (15, "getName", "()Ljava/lang/String;"),
            (16, "getResourceAsStream", "(Ljava/lang/String;)Ljava/io/InputStream;"),
        ],
    ),
    (
        "java/lang/String",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "length", "()I"),
            (11, "charAt", "(I)C"),
            (12, "getChars", "(II[CI)V"),
            (13, "getBytes", "(Ljava/lang/String;)[B"),
            (14, "getBytes", "()[B"),
            (15, "equalsIgnoreCase", "(Ljava/lang/String;)Z"),
            (16, "compareTo", "(Ljava/lang/String;)I"),
            (17, "regionMatches", "(ZILjava/lang/String;II)Z"),
            (18, "startsWith", "(Ljava/lang/String;I)Z"),
            (19, "startsWith", "(Ljava/lang/String;)Z"),
            (20, "endsWith", "(Ljava/lang/String;)Z"),
            (21, "indexOf", "(I)I"),
            (22, "indexOf", "(II)I"),
            (23, "lastIndexOf", "(I)I"),
            (24, "lastIndexOf", "(II)I"),
            (25, "indexOf", "(Ljava/lang/String;)I"),
            (26, "indexOf", "(Ljava/lang/String;I)I"),
            (27, "substring", "(I)Ljava/lang/String;"),
            (28, "substring", "(II)Ljava/lang/String;"),
            (29, "concat", "(Ljava/lang/String;)Ljava/lang/String;"),
            (30, "replace", "(CC)Ljava/lang/String;"),
            (31, "toLowerCase", "()Ljava/lang/String;"),
            (32, "toUpperCase", "()Ljava/lang/String;"),
            (33, "trim", "()Ljava/lang/String;"),
            (34, "toCharArray", "()[C"),
            (35, "intern", "()Ljava/lang/String;"),
        ],
    ),
    (
        "java/lang/StringBuffer",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "length", "()I"),
            (11, "capacity", "()I"),
            (12, "ensureCapacity", "(I)V"),
            (13, "setLength", "(I)V"),
            (14, "charAt", "(I)C"),
            (15, "getChars", "(II[CI)V"),
            (16, "setCharAt", "(IC)V"),
            (17, "append", "(Ljava/lang/Object;)Ljava/lang/StringBuffer;"),
            (18, "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;"),
            (19, "append", "([C)Ljava/lang/StringBuffer;"),
            (20, "append", "([CII)Ljava/lang/StringBuffer;"),
            (21, "append", "(Z)Ljava/lang/StringBuffer;"),
            (22, "append", "(C)Ljava/lang/StringBuffer;"),
            (23, "append", "(I)Ljava/lang/StringBuffer;"),
            (24, "append", "(J)Ljava/lang/StringBuffer;"),
            (25, "append", "(F)Ljava/lang/StringBuffer;"),
            (26, "append", "(D)Ljava/lang/StringBuffer;"),
            (27, "delete", "(II)Ljava/lang/StringBuffer;"),
            (28, "deleteCharAt", "(I)Ljava/lang/StringBuffer;"),
            (29, "insert", "(ILjava/lang/Object;)Ljava/lang/StringBuffer;"),
            (30, "insert", "(ILjava/lang/String;)Ljava/lang/StringBuffer;"),
            (31, "insert", "(I[C)Ljava/lang/StringBuffer;"),
            (32, "insert", "(IZ)Ljava/lang/StringBuffer;"),
            (33, "insert", "(IC)Ljava/lang/StringBuffer;"),
            (34, "insert", "(II)Ljava/lang/StringBuffer;"),
            (35, "insert", "(IJ)Ljava/lang/StringBuffer;"),
            (36, "insert", "(IF)Ljava/lang/StringBuffer;"),
            (37, "insert", "(ID)Ljava/lang/StringBuffer;"),
            (38, "reverse", "()Ljava/lang/StringBuffer;"),
        ],
    ),
    (
        "java/lang/Thread",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "start", "()V"),
            (11, "run", "()V"),
            (12, "interrupt", "()V"),
            (13, "isAlive", "()Z"),
            (14, "setPriority", "(I)V"),
            (15, "getPriority", "()I"),
            (16, "getName", "()Ljava/lang/String;"),
            (17, "join", "()V"),
        ],
    ),
    (
        "java/lang/Integer",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "byteValue", "()B"),
            (11, "shortValue", "()S"),
            (12, "intValue", "()I"),
            (13, "longValue", "()J"),
            (14, "floatValue", "()F"),
            (15, "doubleValue", "()D"),
        ],
    ),
    (
        "java/lang/Exception",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
        ],
    ),
    (
        "java/lang/Throwable",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "getMessage", "()Ljava/lang/String;"),
            (11, "printStackTrace", "()V"),
        ],
    ),
    (
        "java/lang/Runtime",
        &[
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "exit", "(I)V"),
            (11, "freeMemory", "()J"),
            (12, "totalMemory", "()J"),
            (13, "gc", "()V"),
        ],
    ),
    (
        "java/lang/System",
        &[
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
        ],
    ),
    (
        "java/util/Vector",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "copyInto", "([Ljava/lang/Object;)V"),
            (11, "trimToSize", "()V"),
            (12, "ensureCapacity", "(I)V"),
            (13, "setSize", "(I)V"),
            (14, "capacity", "()I"),
            (15, "size", "()I"),
            (16, "isEmpty", "()Z"),
            (17, "elements", "()Ljava/util/Enumeration;"),
            (18, "contains", "(Ljava/lang/Object;)Z"),
            (19, "indexOf", "(Ljava/lang/Object;)I"),
            (20, "indexOf", "(Ljava/lang/Object;I)I"),
            (21, "lastIndexOf", "(Ljava/lang/Object;)I"),
            (22, "lastIndexOf", "(Ljava/lang/Object;I)I"),
            (23, "elementAt", "(I)Ljava/lang/Object;"),
            (24, "firstElement", "()Ljava/lang/Object;"),
            (25, "lastElement", "()Ljava/lang/Object;"),
            (26, "setElementAt", "(Ljava/lang/Object;I)V"),
            (27, "removeElementAt", "(I)V"),
            (28, "insertElementAt", "(Ljava/lang/Object;I)V"),
            (29, "addElement", "(Ljava/lang/Object;)V"),
            (30, "removeElement", "(Ljava/lang/Object;)Z"),
            (31, "removeAllElements", "()V"),
        ],
    ),
    (
        "java/util/Hashtable",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "size", "()I"),
            (11, "isEmpty", "()Z"),
            (12, "keys", "()Ljava/util/Enumeration;"),
            (13, "elements", "()Ljava/util/Enumeration;"),
            (14, "contains", "(Ljava/lang/Object;)Z"),
            (15, "containsKey", "(Ljava/lang/Object;)Z"),
            (16, "get", "(Ljava/lang/Object;)Ljava/lang/Object;"),
            (17, "rehash", "()V"),
            (18, "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"),
            (19, "remove", "(Ljava/lang/Object;)Ljava/lang/Object;"),
            (20, "clear", "()V"),
        ],
    ),
    (
        "java/util/Random",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "setSeed", "(J)V"),
            (11, "next", "(I)I"),
            (12, "nextInt", "()I"),
            (13, "nextInt", "(I)I"),
            (14, "nextLong", "()J"),
            (15, "nextFloat", "()F"),
            (16, "nextDouble", "()D"),
        ],
    ),
    (
        "java/util/Calendar",
        &[
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "after", "(Ljava/lang/Object;)Z"),
            (11, "before", "(Ljava/lang/Object;)Z"),
            (12, "computeFields", "()V"),
            (13, "computeTime", "()V"),
            (14, "getGreatestMinimum", "(I)I"),
            (15, "getLeastMaximum", "(I)I"),
            (16, "getMaximum", "(I)I"),
            (17, "getMinimum", "(I)I"),
            (18, "complete", "()V"),
            (19, "get", "(I)I"),
            (20, "getFirstDayOfWeek", "()I"),
            (21, "getMinimalDaysInFirstWeek", "()I"),
            (22, "getTime", "()Ljava/util/Date;"),
            (23, "getTimeInMillis", "()J"),
            (24, "getTimeZone", "()Ljava/util/TimeZone;"),
            (25, "internalGet", "(I)I"),
            (26, "isLenient", "()Z"),
            (27, "isSet", "(I)Z"),
            (28, "set", "(II)V"),
            (29, "setTime", "(Ljava/util/Date;)V"),
            (30, "setTimeInMillis", "(J)V"),
            (31, "setTimeZone", "(Ljava/util/TimeZone;)V"),
            (32, "set", "(III)V"),
        ],
    ),
    (
        "java/util/Date",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "getTime", "()J"),
            (11, "setTime", "(J)V"),
        ],
    ),
    (
        "java/util/Timer",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "schedule", "(Ljava/util/TimerTask;J)V"),
            (11, "schedule", "(Ljava/util/TimerTask;Ljava/util/Date;)V"),
            (12, "schedule", "(Ljava/util/TimerTask;JJ)V"),
            (13, "schedule", "(Ljava/util/TimerTask;Ljava/util/Date;J)V"),
            (14, "scheduleAtFixedRate", "(Ljava/util/TimerTask;JJ)V"),
            (15, "scheduleAtFixedRate", "(Ljava/util/TimerTask;Ljava/util/Date;J)V"),
            (16, "cancel", "()V"),
        ],
    ),
    (
        "java/io/InputStream",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "read", "()I"),
            (11, "read", "([B)I"),
            (12, "read", "([BII)I"),
            (13, "skip", "(J)J"),
            (14, "available", "()I"),
            (15, "close", "()V"),
            (16, "mark", "(I)V"),
            (17, "reset", "()V"),
            (18, "markSupported", "()Z"),
        ],
    ),
    (
        "java/io/DataInputStream",
        &[
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "read", "()I"),
            (11, "read", "([B)I"),
            (12, "read", "([BII)I"),
            (13, "skip", "(J)J"),
            (14, "available", "()I"),
            (15, "close", "()V"),
            (16, "mark", "(I)V"),
            (17, "reset", "()V"),
            (18, "markSupported", "()Z"),
            (19, "readFully", "([B)V"),
            (20, "readFully", "([BII)V"),
            (21, "skipBytes", "(I)I"),
            (22, "readBoolean", "()Z"),
            (23, "readByte", "()B"),
            (24, "readUnsignedByte", "()I"),
            (25, "readShort", "()S"),
            (26, "readUnsignedShort", "()I"),
            (27, "readChar", "()C"),
            (28, "readInt", "()I"),
            (29, "readLong", "()J"),
            (30, "readFloat", "()F"),
            (31, "readDouble", "()D"),
            (32, "readUTF", "()Ljava/lang/String;"),
        ],
    ),
    (
        "java/io/OutputStream",
        &[
            (0, "<init>", "()V"),
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "write", "(I)V"),
            (11, "write", "([B)V"),
            (12, "write", "([BII)V"),
            (13, "flush", "()V"),
            (14, "close", "()V"),
        ],
    ),
    (
        "java/io/DataOutputStream",
        &[
            (1, "getClass", "()Ljava/lang/Class;"),
            (2, "hashCode", "()I"),
            (3, "equals", "(Ljava/lang/Object;)Z"),
            (4, "toString", "()Ljava/lang/String;"),
            (5, "notify", "()V"),
            (6, "notifyAll", "()V"),
            (7, "wait", "(J)V"),
            (8, "wait", "(JI)V"),
            (9, "wait", "()V"),
            (10, "write", "(I)V"),
            (12, "write", "([BII)V"),
            (13, "flush", "()V"),
            (14, "close", "()V"),
            (15, "writeBoolean", "(Z)V"),
            (16, "writeByte", "(I)V"),
            (17, "writeShort", "(I)V"),
            (18, "writeChar", "(I)V"),
            (19, "writeInt", "(I)V"),
            (20, "writeLong", "(J)V"),
            (21, "writeFloat", "(F)V"),
            (22, "writeDouble", "(D)V"),
            (23, "writeChars", "(Ljava/lang/String;)V"),
            (24, "writeUTF", "(Ljava/lang/String;)V"),
        ],
    ),
    (
        "org/kwis/msp/lcdui/Card",
        &[
            (0, "<init>", "()V"),
            (10, "move", "(II)V"),
            (11, "resize", "(II)V"),
            (12, "getWidth", "()I"),
            (13, "getHeight", "()I"),
            (14, "getX", "()I"),
            (15, "getY", "()I"),
            (16, "showNotify", "(Z)V"),
            (17, "keyNotify", "(II)Z"),
            (18, "pointerNotify", "(III)Z"),
            (19, "paint", "(Lorg/kwis/msp/lcdui/Graphics;)V"),
            (20, "repaint", "(IIII)V"),
            (21, "repaint", "()V"),
            (22, "serviceRepaints", "()V"),
            (23, "isShown", "()Z"),
            (24, "getDisplay", "()Lorg/kwis/msp/lcdui/Display;"),
        ],
    ),
    (
        "org/kwis/msp/lcdui/Display",
        &[
            (10, "pushCard", "(Lorg/kwis/msp/lcdui/Card;)V"),
            (11, "popCard", "()Lorg/kwis/msp/lcdui/Card;"),
            (12, "removeCard", "(Lorg/kwis/msp/lcdui/Card;)Z"),
            (13, "removeAllCards", "()V"),
            (14, "countCard", "()I"),
            (15, "callSerially", "(Ljava/lang/Runnable;)V"),
            (16, "callSerially", "(Ljava/lang/Runnable;I)V"),
            (17, "getDockedCard", "()Lorg/kwis/msp/lcdui/Card;"),
            (18, "setDockedCard", "(Lorg/kwis/msp/lcdui/Card;I)V"),
            (19, "isColor", "()Z"),
            (20, "numColors", "()I"),
            (21, "hasPointerEvents", "()Z"),
            (22, "hasPointerMotionEvents", "()Z"),
            (23, "hasRepeatEvents", "()Z"),
            (24, "getWidth", "()I"),
            (25, "getHeight", "()I"),
            (26, "isDoubleBuffered", "()Z"),
            (27, "getBitsPerPixel", "()I"),
            (28, "flush", "()V"),
            (29, "addJletEventListener", "(Lorg/kwis/msp/lcdui/JletEventListener;)V"),
            (30, "removeJletEventListener", "(Lorg/kwis/msp/lcdui/JletEventListener;)V"),
            (31, "grabKey", "(ILorg/kwis/msp/lcdui/JletEventListener;)V"),
            (32, "ungrabKey", "(I)V"),
            (41, "enableFullOEMDisplayArea", "(I)I"),
            (42, "enableOEMDisplayArea", "(IIIII)I"),
            (43, "enableOEMDisplayArea", "(IIIIIZ)I"),
            (44, "disableOEMDisplayArea", "(I)I"),
            (45, "activateCurrentDisplay", "()I"),
            (46, "getRotation", "()I"),
            (47, "setAnnunBackground", "(Lorg/kwis/msp/lcdui/Image;)V"),
            (48, "grabKey0", "(II)V"),
            (49, "ungrabKey0", "(I)V"),
        ],
    ),
    (
        "org/kwis/msp/lcdui/Graphics",
        &[
            (10, "clipRect", "(IIII)V"),
            (11, "drawChar", "(CIII)V"),
            (12, "drawChars", "([CIIIII)V"),
            (13, "drawImage", "(Lorg/kwis/msp/lcdui/Image;III)V"),
            (14, "drawLine", "(IIII)V"),
            (15, "drawRect", "(IIII)V"),
            (16, "drawRoundRect", "(IIIIII)V"),
            (17, "drawString", "(Ljava/lang/String;III)V"),
            (18, "drawSubstring", "(Ljava/lang/String;IIIII)V"),
            (19, "drawArc", "(IIIIII)V"),
            (20, "fillArc", "(IIIIII)V"),
            (21, "fillRect", "(IIII)V"),
            (22, "fillRoundRect", "(IIIIII)V"),
            (23, "fillPolygon", "([I[I)V"),
            (24, "getBlueComponent", "()I"),
            (25, "getClipHeight", "()I"),
            (26, "getClipWidth", "()I"),
            (27, "getClipX", "()I"),
            (28, "getClipY", "()I"),
            (29, "getColor", "()I"),
            (30, "getFont", "()Lorg/kwis/msp/lcdui/Font;"),
            (31, "getGrayScale", "()I"),
            (32, "getGreenComponent", "()I"),
            (33, "getRedComponent", "()I"),
            (34, "getStrokeStyle", "()I"),
            (35, "getTranslateX", "()I"),
            (36, "getTranslateY", "()I"),
            (37, "setClip", "(IIII)V"),
            (38, "setColor", "(I)V"),
            (39, "setColor", "(III)V"),
            (40, "setFont", "(Lorg/kwis/msp/lcdui/Font;)V"),
            (41, "setGrayScale", "(I)V"),
            (42, "setStrokeStyle", "(I)V"),
            (43, "translate", "(II)V"),
            (44, "getPixel", "(II)I"),
            (45, "setPixel", "(II)V"),
            (46, "getPixels", "(IIII[BII)V"),
            (47, "getRGBPixels", "(IIII[III)V"),
            (48, "setPixels", "(IIII[BII)V"),
            (49, "setRGBPixels", "(IIII[III)V"),
            (50, "copyArea", "(IIIIII)V"),
            (51, "drawPolygon", "([I[I)V"),
            (52, "reset", "()V"),
            (53, "setAlpha", "(I)V"),
            (54, "getAlpha", "()I"),
            (55, "setXORMode", "(Z)V"),
            (56, "isXORMode", "()Z"),
            (57, "encodeImage", "(IIII)[B"),
            (58, "setEdgeColor", "(I)V"),
        ],
    ),
    (
        "org/kwis/msp/lcdui/Image",
        &[
            (0, "<init>", "()V"),
            (10, "getGraphics", "()Lorg/kwis/msp/lcdui/Graphics;"),
            (11, "getHeight", "()I"),
            (12, "getWidth", "()I"),
            (13, "isMutable", "()Z"),
            (14, "isAnimated", "()Z"),
            (15, "play", "(Lorg/kwis/msp/lcdui/ImageObserver;)V"),
            (16, "stop", "()V"),
            (17, "drawImage", "(Lorg/kwis/msp/lcdui/Image;IIIIIIII)V"),
            (18, "createSubImage", "(IIIIZ)Lorg/kwis/msp/lcdui/Image;"),
            (19, "setTransparentColor", "(I)V"),
            (21, "getPlayTime", "()I"),
            (22, "finalize", "()V"),
        ],
    ),
    (
        "org/kwis/msp/lcdui/Font",
        &[
            (10, "charsWidth", "([CII)I"),
            (11, "charWidth", "(C)I"),
            (12, "getBaselinePosition", "()I"),
            (13, "getFace", "()I"),
            (14, "getHeight", "()I"),
            (15, "getSize", "()I"),
            (16, "getStyle", "()I"),
            (17, "isBold", "()Z"),
            (18, "isItalic", "()Z"),
            (19, "isPlain", "()Z"),
            (20, "isUnderlined", "()Z"),
            (21, "stringWidth", "(Ljava/lang/String;)I"),
            (22, "substringWidth", "(Ljava/lang/String;II)I"),
        ],
    ),
    (
        "org/kwis/msp/lcdui/Jlet",
        &[
            (10, "getCurrentProgramID", "()I"),
            (11, "startApp", "([Ljava/lang/String;)V"),
            (12, "pauseApp", "()V"),
            (13, "resumeApp", "()V"),
            (14, "destroyApp", "(Z)V"),
            (15, "notifyDestroyed", "()V"),
            (16, "getAppProperty", "(Ljava/lang/String;)Ljava/lang/String;"),
            (17, "getEventQueue", "()Lorg/kwis/msp/lcdui/EventQueue;"),
            (18, "getDisplay", "(Ljava/lang/String;)Lorg/kwis/msp/lcdui/Display;"),
            (19, "setRotatedDisplay", "(Lorg/kwis/msp/lcdui/Display;)V"),
            (20, "getState", "()I"),
        ],
    ),
    (
        "org/kwis/msp/lwc/Component",
        &[
            (4, "toString", "()Ljava/lang/String;"),
            (10, "getWidth", "()I"),
            (11, "getHeight", "()I"),
            (12, "canHandleInput", "()Z"),
            (13, "hasFocus", "()Z"),
            (14, "configure", "(IIIII)V"),
            (15, "getX", "()I"),
            (16, "getY", "()I"),
            (17, "calcPreferredSize", "(I)V"),
            (18, "getPreferredHeight", "()I"),
            (19, "getPreferredHeight", "(I)I"),
            (20, "getPreferredWidth", "()I"),
            (21, "setBackground", "(I)V"),
            (22, "setForeground", "(I)V"),
            (23, "getBackground", "()I"),
            (24, "getForeground", "()I"),
            (25, "paintContent", "(Lorg/kwis/msp/lcdui/Graphics;)V"),
            (26, "isValid", "()Z"),
            (27, "invalidate", "()V"),
            (28, "validate", "()V"),
            (29, "layout", "()V"),
            (30, "setFocus", "()V"),
            (31, "focusNotify", "(Z)V"),
            (32, "keyNotify", "(II)Z"),
            (33, "pointerNotify", "(III)Z"),
            (34, "showNotify", "(Z)V"),
            (35, "repaint", "()V"),
            (36, "isShown", "()Z"),
            (37, "processEvent", "(IIII)Z"),
            (38, "repaint", "(IIII)V"),
            (39, "serviceRepaints", "()V"),
            (40, "getXOnScreen", "()I"),
            (41, "getYOnScreen", "()I"),
            (42, "getCard", "()Lorg/kwis/msp/lcdui/Card;"),
            (43, "setEventListener", "(Lorg/kwis/msp/lwc/EventListener;Ljava/lang/Object;)V"),
            (44, "getDisplay", "()Lorg/kwis/msp/lcdui/Display;"),
        ],
    ),
    (
        "org/kwis/msp/lwc/AnnunciatorComponent",
        &[
            (29, "layout", "()V"),
            (45, "addComponent", "(ILorg/kwis/msp/lwc/Component;)V"),
            (49, "removeComponent", "(Lorg/kwis/msp/lwc/Component;)V"),
            (55, "paint", "(Lorg/kwis/msp/lcdui/Graphics;)V"),
            (64, "show", "()V"),
            (65, "hide", "()V"),
        ],
    ),
    (
        "org/kwis/msp/lwc/ShellComponent",
        &[
            (0, "<init>", "()V"),
            (14, "configure", "(IIIII)V"),
            (15, "getX", "()I"),
            (16, "getY", "()I"),
            (29, "layout", "()V"),
            (32, "keyNotify", "(II)Z"),
            (33, "pointerNotify", "(III)Z"),
            (34, "showNotify", "(Z)V"),
            (36, "isShown", "()Z"),
            (37, "processEvent", "(IIII)Z"),
            (38, "repaint", "(IIII)V"),
            (39, "serviceRepaints", "()V"),
            (42, "getCard", "()Lorg/kwis/msp/lcdui/Card;"),
            (45, "addComponent", "(ILorg/kwis/msp/lwc/Component;)V"),
            (46, "addComponent", "(Lorg/kwis/msp/lwc/Component;)I"),
            (49, "removeComponent", "(Lorg/kwis/msp/lwc/Component;)V"),
            (50, "removeAllComponents", "()V"),
            (53, "getNextTraversalComponent", "()Lorg/kwis/msp/lwc/Component;"),
            (54, "getPrevTraversalComponent", "()Lorg/kwis/msp/lwc/Component;"),
            (58, "controlInset", "(Z)V"),
            (64, "show", "()V"),
            (65, "hide", "()V"),
            (66, "setTitle", "(Lorg/kwis/msp/lwc/Component;)V"),
            (67, "getTitle", "()Lorg/kwis/msp/lwc/Component;"),
            (68, "getWorkComponent", "()Lorg/kwis/msp/lwc/Component;"),
            (69, "setWorkComponent", "(Lorg/kwis/msp/lwc/Component;)V"),
            (70, "setCommand", "(Lorg/kwis/msp/lwc/Component;Z)V"),
            (71, "getCommand", "()Lorg/kwis/msp/lwc/Component;"),
            (72, "setTitle", "(Ljava/lang/String;)V"),
            (73, "grabKey", "(I)V"),
            (74, "ungrabKey", "(I)V"),
            (75, "setGrabKeyListener", "(Lorg/kwis/msp/lwc/GrabKeyListener;Ljava/lang/Object;)V"),
        ],
    ),
    (
        "org/kwis/msp/lwc/TextBoxComponent",
        &[
            (14, "configure", "(IIIII)V"),
            (18, "getPreferredHeight", "()I"),
            (19, "getPreferredHeight", "(I)I"),
            (20, "getPreferredWidth", "()I"),
            (25, "paintContent", "(Lorg/kwis/msp/lcdui/Graphics;)V"),
            (31, "focusNotify", "(Z)V"),
            (32, "keyNotify", "(II)Z"),
            (45, "setString", "(Ljava/lang/String;)V"),
            (46, "setMaxLength", "(I)V"),
            (49, "insert", "([CIII)V"),
            (50, "delete", "(II)V"),
            (52, "setFont", "(Lorg/kwis/msp/lcdui/Font;)V"),
        ],
    ),
    (
        "org/kwis/msp/io/File",
        &[
            (10, "openInputStream", "()Ljava/io/InputStream;"),
            (11, "openDataInputStream", "()Ljava/io/DataInputStream;"),
            (12, "openOutputStream", "()Ljava/io/OutputStream;"),
            (13, "openDataOutputStream", "()Ljava/io/DataOutputStream;"),
            (14, "close", "()V"),
            (15, "write", "(I)I"),
            (16, "write", "([B)I"),
            (17, "write", "([BII)I"),
            (18, "read", "()I"),
            (19, "read", "([B)I"),
            (20, "read", "([BII)I"),
            (21, "seek", "(I)V"),
            (22, "sizeOf", "()I"),
            (23, "tell", "()I"),
        ],
    ),
    ("org/kwis/msp/io/FileSystem", &[(0, "<init>", "()V")]),
    (
        "org/kwis/msp/media/Clip",
        &[
            (12, "free", "()V"),
            (71, "getType", "()Ljava/lang/String;"),
            (72, "setPosition", "(I)Z"),
            (73, "getPosition", "()I"),
            (74, "setStopTime", "(I)Z"),
            (75, "getStopTime", "()I"),
            (76, "getVolume", "()I"),
            (77, "setVolume", "(I)Z"),
            (78, "setListener", "(Lorg/kwis/msp/media/PlayListener;)V"),
            (79, "setListener", "(Lorg/kwis/msp/media/PlayerListener;)V"),
        ],
    ),
    ("org/kwis/msp/media/Player", &[(0, "<init>", "()V")]),
    ("org/kwis/msf/io/Network", &[(0, "<init>", "()V")]),
    ("org/kwis/msf/io/URL", &[(0, "<init>", "()V")]),
];

/// The method a class puts in `slot`, if the layout is known.
///
/// This is what answers a call the application makes on an object of a class
/// it never imported - `getClass().getResourceAsStream(...)` reaches
/// `java/lang/Class` slot 16, and nothing the application registers says what
/// that is.
pub fn platform_method(class: &str, slot: u32) -> Option<(&'static str, &'static str)> {
    let slots = PLATFORM_DISPATCH_SLOTS.iter().find(|(known, _)| *known == class)?.1;

    slots
        .iter()
        .find(|(known, _, _)| *known == slot)
        .map(|(_, name, descriptor)| (*name, *descriptor))
}

/// The slot `class.name descriptor` occupies, if the layout is known.
pub fn platform_slot(class: &str, name: &str, descriptor: &str) -> Option<u32> {
    let slots = PLATFORM_DISPATCH_SLOTS.iter().find(|(known, _)| *known == class)?.1;

    slots
        .iter()
        .find(|(_, known_name, known_descriptor)| *known_name == name && *known_descriptor == descriptor)
        .map(|(slot, _, _)| *slot)
}

#[cfg(test)]
mod tests {
    use super::{PLATFORM_DISPATCH_SLOTS, platform_slot};

    /// The ten slots before a class's own are fixed, so every table has to
    /// agree about them.
    #[test]
    fn object_slots_are_the_same_everywhere() {
        for (class, slots) in PLATFORM_DISPATCH_SLOTS {
            for (slot, name, descriptor) in slots.iter().filter(|(slot, _, _)| (1..10).contains(slot)) {
                let object = platform_slot("java/lang/Object", name, descriptor);

                assert_eq!(object, Some(*slot), "{class} puts {name}{descriptor} at slot {slot}");
            }
        }
    }

    #[test]
    fn a_class_uses_each_slot_once() {
        for (class, slots) in PLATFORM_DISPATCH_SLOTS {
            for (index, (slot, _, _)) in slots.iter().enumerate() {
                assert!(
                    slots[..index].iter().all(|(earlier, _, _)| earlier != slot),
                    "{class} uses slot {slot} twice"
                );
            }
        }
    }

    #[test]
    fn a_slot_names_the_method_the_class_put_there() {
        use super::platform_method;

        assert_eq!(
            platform_method("java/lang/Class", 16),
            Some(("getResourceAsStream", "(Ljava/lang/String;)Ljava/io/InputStream;"))
        );
        assert_eq!(platform_method("java/lang/Object", 2), Some(("hashCode", "()I")));
        assert_eq!(platform_method("java/lang/Class", 999), None);
        assert_eq!(platform_method("no/such/Class", 1), None);
    }

    #[test]
    fn known_layouts_start_at_ten() {
        assert_eq!(platform_slot("java/lang/String", "compareTo", "(Ljava/lang/String;)I"), Some(16));
        assert_eq!(platform_slot("org/kwis/msp/lcdui/Card", "showNotify", "(Z)V"), Some(16));
        assert_eq!(platform_slot("java/lang/Thread", "start", "()V"), Some(10));
        assert_eq!(platform_slot("java/lang/String", "nonesuch", "()V"), None);
        assert_eq!(platform_slot("no/such/Class", "toString", "()Ljava/lang/String;"), None);
    }
}
